### read the Authors
GET http://localhost:4004/odata/v4/BookSRV/Books HTTP/1.1
### create
POST http://localhost:4004/BookSRV/Books HTTP/1.1
Content-Type: application/json

    {
        "isbn": "9780060850590",
      "title": "The Catcher in the Rye",
      "quantity": 12,
      "price": 8.49,
      "pages": 288,
      "author": "J.D. Salinger",
      "status": "Out of Stock",
      "users_id": 4

    }


### read the Books

GET http://localhost:4004/odata/v4/app-library/Books HTTP/1.1

### read the BooksLoan
GET http://localhost:4004/odata/v4/app-library/BooksLoan HTTP/1.1

### read the ReservedBooks

GET http://localhost:4004/odata/v4/app-library/ReservedBooks HTTP/1.1

### filters

GET http://localhost:4004/odata/v4/app-library/Books?$expand=authors HTTP/1.1

###filters on books
GET http://localhost:4004/odata/v4/app-library/Authors?$expand=books HTTP/1.1

###Delete data

DELETE  http://localhost:4004/odata/v4/app-library/Books/1 HTTP/1.1



